# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Todo'),
        ),
    ]
